version: '3'
services:
    mongo:
        container_name: mongo
        image: mongo
        ports:
            - '${DB_PORT}:27017'
        restart: always
        volumes:
            - db-data:/data/db
        # environment:
        #     MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
        #     MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
    server: 
        container_name: server
        restart: always
        build: .
        ports:
            - '${SERVER_PORT}:3000'
        links:
            - mongo
        volumes:
            - ./src:/usr/src/app/src
volumes:
    db-data: