const METRIC_ENUM = {
    METRIC: 'METRIC',
    IMPERIAL: 'IMPERIAL'
}

const GENDER_ENUM = {
    M: 'M',
    W: 'W'
}

const ACTIVITY_TYPE_ENUM = {
    POST_CREATED: 'POST_CREATED',
    FOLLOWED: 'FOLLOWED',
    TRAINING_FINISHED: 'TRAINING_FINISHED',
    TRAINING_CREATED: 'TRAINING_CREATED',
    TRAINING_SHARED: 'TRAINING_SHARED',
    PERSONAL_DATA_UPDATED: 'PERSONAL_DATA_UPDATED',
    MEAL_ADDED: 'MEAL_ADDED',
    MEAL_UPDATED: 'MEAL_UPDATED'
}

// TODO: ADD MORE GROUPS
const MUSCLE_GROUP_TYPE_ENUM = {
    CHEST: 'CHEST',
    ARMS: 'ARMS',
    LEGS: 'LEGS',
}

export default {
    METRIC_ENUM,
    GENDER_ENUM,
    MUSCLE_GROUP_TYPE_ENUM,
    ACTIVITY_TYPE_ENUM,
}